experiment:
  name: ier_retd3_halfcheetah
  framework: IER
  selection_strategy: episode_reward

environment:
  gym: openai
  task: HalfCheetah-v4
  domain: ""

algorithm:
  name: ReTD3

training:
  seeds: [10]
